Repository stevent-team/totp, pull requests merged in 2023-01, with the labels that each got.

#2 Move from vite to tsc/esbuild
  .changeset/afraid-ties-look.md
  package.json
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: chore

#4 Fix release workflow
  .github/workflows/release.yml
  package.json
Labels: bug, chore

#5 Move from esbuild to tsup
  .changeset/healthy-knives-hide.md
  package.json
  tsup.config.ts
  yarn.lock
Labels: chore

#6 Update exported option types
  .changeset/strange-jobs-whisper.md
  README.md
  lib/main.ts
Labels: enhancement

#8 Allow null for outputDigits option in the type
  .changeset/grumpy-bobcats-visit.md
  lib/main.ts
Labels: bug
